### ISSUE TITLE
whereOccurresBetween doesn't consider Start_at Date

### ISSUE THREAD

**Issue by Tarhex** [mohammedmanssour/laravel-recurring-models#1]
### What happened?

I created a recurring model, and I was able to query it using `whereOccurresBetween` successfully using dates in the future since I didn't set an end date. When I set the query dates to earlier in the year, I still got the same repetitions which is not suppose to be since the `start_at` was set to today. The query is not considering the `start_at` while returning the output of the query.

### How to reproduce the bug

\Log::info (\App\Models\Schedule::whereOccurresBetween(Carbon::make('2023-01-01'), Carbon::make('2023-02-01'))->get());

### Package Version

0.3.1

### PHP Version

8.2.0

### Laravel Version

10.9.0

**Comment by mohammedmanssour** [comment]
@Tarhex Thanks for reporting the bug.
will be looking into it this Weekend 👍

**Comment by Rooligan** [comment]
I've had the same problem. I've got a fix for it and two additional tests for this situation.

**Comment by jpmurray** [comment]
> I've had the same problem. I've got a fix for it and two additional tests for this situation.

Are you looking to do a PR ?

**Comment by jpmurray** [comment]
I don't think defining `repetitionBaseDate` on the model works at all either...

**Comment by mohammedmanssour** [comment]
Should be fixed with PR #5
