### ISSUE TITLE
[Bug]: Conflicts with other packages in Laravel 11

### ISSUE THREAD

**Issue by Sergiobop** [mohammedmanssour/laravel-recurring-models#14]
### What happened?

Trying to install/update my project to Laravel 11.

### How to reproduce the bug

mohammedmanssour/laravel-recurring-models v0.5.1 requires illuminate/contracts ^10.0 (and other packages that are updated require 11.0)

### Package Version

0.5.1

### PHP Version

8.3

### Laravel Version

11

**Comment by mohammedmanssour** [comment]
Should be fixed with #16
