### ISSUE TITLE
Adding more precise repeating

### ISSUE THREAD

**Issue by theveloperspl** [mohammedmanssour/laravel-recurring-models#2]
### What happened?

Hello, you have no discussion page so I ask here.
Do you plan to add hourly (most useable), minutely or even secondly repeating feature?

### How to reproduce the bug

-

### Package Version

-

### PHP Version

-

### Laravel Version

-

**Comment by mohammedmanssour** [comment]
Hi @theveloperspl 

Thanks for binging that up. I'm not planning to add such repetition settings since I won't make use of it personally. but I welcome PRs.
