### ISSUE TITLE
[Featue request]: Get the next upcoming repetition of a model

### ISSUE THREAD

**Issue by jpmurray** [mohammedmanssour/laravel-recurring-models#4]
I'd like to know if it would be possible to have a function that would return a Carbon object of the next occurence for a model ?

On a model has repetition in the database already, a `$model->next_repetition()` that would return the info as a Carbon object...

**Comment by EriBloo** [comment]
This should be added in [this PR](https://github.com/mohammedmanssour/laravel-recurring-models/pull/15). I wrote it slightly differently than you hoped, but you should achieve the same effect.

**Comment by mohammedmanssour** [comment]
Should be done in PR #15
